# Generated by Django 4.0.4 on 2022-05-25 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='review_content',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='review_title',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='review',
            name='review_image',
        ),
        migrations.AddField(
            model_name='review',
            name='image',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
