# Generated by Django 4.0.4 on 2022-05-25 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='orderstatus',
            table='orders_tatuses',
        ),
    ]
