# Generated by Django 4.0.4 on 2022-05-25 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_orderstatus_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='orderstatus',
            table='order_statuses',
        ),
    ]
