# Generated by Django 4.0.4 on 2022-05-25 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_productimage_product_image'),
        ('orders', '0003_alter_orderstatus_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderItime',
            new_name='OrderItem',
        ),
    ]
