# Generated by Django 4.0.4 on 2022-05-25 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_delivery_address_alter_user_email'),
        ('products', '0004_rename_product_content_product_content_and_more'),
        ('orders', '0004_rename_orderitime_orderitem'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cart',
            unique_together={('user', 'product')},
        ),
    ]
