# Generated by Django 4.0.4 on 2022-05-25 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_productimage_table_alter_producttheme_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='product_image',
            field=models.CharField(max_length=300),
        ),
    ]
