# Generated by Django 4.0.4 on 2022-05-25 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_productimage_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_content',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='productimage',
            old_name='product_image',
            new_name='image',
        ),
        migrations.AlterModelTable(
            name='producttheme',
            table='product_themes',
        ),
    ]
