# Generated by Django 4.0.4 on 2022-05-27 04:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_rename_product_content_product_content_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='content',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='people',
            new_name='prep_time',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='selling_price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='setting_time',
            new_name='serving',
        ),
        migrations.RemoveField(
            model_name='product',
            name='discount_price',
        ),
        migrations.CreateModel(
            name='Spice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=15)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
            options={
                'db_table': 'spices',
            },
        ),
    ]
