# Generated by Django 4.0.4 on 2022-05-26 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_rename_content_product_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='setting_time',
            new_name='prep_time',
        ),
    ]
